up

diff --git a/.github/workflows/preview.yaml b/.github/workflows/preview.yaml
--- a/.github/workflows/preview.yaml
+++ b/.github/workflows/preview.yaml
@@ -18,9 +18,15 @@ jobs:
         run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
       - name: Deploy Project Artifacts to Vercel
         id: deploy
-        run: echo "url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT
-      - if: ${{ job.status == 'success' }}
-        uses: actions/github-script@v3
+        run: |
+          if [ -f snyk-code.sarif ]; then
+            echo "Snyk Code test failed. Skipping deployment."
+            exit 1
+          else
+            echo "Snyk Code test passed. Deploying to Vercel."
+            vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
+          fi
+      - uses: actions/github-script@v3
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
@@ -30,3 +36,4 @@ jobs:
               repo: context.repo.repo,
               body: 'The preview URL is: ${{ steps.deploy.outputs.url }}.'
             });
+
diff --git a/.github/workflows/snyk-container.yml b/.github/workflows/snyk-container.yml
--- a/.github/workflows/snyk-container.yml
+++ b/.github/workflows/snyk-container.yml
@@ -21,7 +21,16 @@ jobs:
       - name: Set up Snyk CLI to check for security issues
         uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
       - name: Snyk Code test
-        run: snyk code test --sarif > snyk-code.sarif || echo "Erreur Snyk : $?"
+        id: snyk-code-test
+        run: |
+          snyk code test --sarif > snyk-code.sarif || exit 0 # Ignore error and continue execution
+          export SNYK_EXIT_CODE=$?
+          if [ $SNYK_EXIT_CODE -ne 0 ]; then
+            echo "Snyk Code test failed with exit code $SNYK_EXIT_CODE."
+            echo "Error details:"
+            cat snyk-code.sarif
+            exit $SNYK_EXIT_CODE
+          fi
       - name: Upload result to GitHub Code Scanning
         if: always()
         uses: github/codeql-action/upload-sarif@v2
