up

diff --git a/.github/workflows/snyk-container.yml b/.github/workflows/snyk-container.yml
--- a/.github/workflows/snyk-container.yml
+++ b/.github/workflows/snyk-container.yml
@@ -1,4 +1,3 @@
-
 name: Snyk Security
 env:
   SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
@@ -7,10 +6,8 @@ on:
   pull_request:
     branches: ["main"]
 
-
 permissions:
   contents: read
-
 
 jobs:
   snyk:
@@ -24,7 +21,9 @@ jobs:
       - name: Set up Snyk CLI to check for security issues
         uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
       - name: Snyk Code test
-        run: snyk code test --sarif > snyk-code.sarif # || true
+        run: |
+          snyk code test --sarif > snyk-code.sarif || true
+          echo "::set-output name=error-details::$(cat snyk-code.sarif)"
       - name: Upload result to GitHub Code Scanning
         if: always()
         uses: github/codeql-action/upload-sarif@v2
